project:
  name: quickstart-cmmc-microsoft-activedirectory
  owner: quickstart-eng@amazon.com
  package_lambda: false
  regions:
  - ap-northeast-1
  - ap-northeast-2
  - ap-south-1
  - ap-southeast-1
  - ap-southeast-2
  - ca-central-1
  - eu-central-1
  - eu-west-1
  - eu-west-2
  # - eu-west-3
  - sa-east-1
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
tests:
  cmmc-ad:
    parameters:
      AdministratorPassword: $[taskcat_genpass_16]
      AvailabilityZones: $[taskcat_genaz_2]
      CAAdministratorPassword: $[taskcat_genpass_16]
      CreateS3Buckets: "no"
      CRLS3BucketName: override
      DomainAdminPassword: $[taskcat_genpass_16]
      GPOS3BucketName: override
      KeyPairName: $[taskcat_getkeypair]
      LogsS3BucketName: override
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      RDGWCIDR: 10.0.0.0/16
      RestoreModePassword: $[taskcat_genpass_16]
    regions:
    - us-east-2
    template: templates/ad-main-1-ssm.template.yaml
